project:
  name: quickstart-qingcloud-kubesphere
  owner: quickstart-eng@amazon.com
  build_submodules: true
  package_lambda: true
  regions:
  - us-west-2
  - us-east-1
  - us-east-2
  - sa-east-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-north-1
  - eu-central-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ca-central-1
  - ap-east-1
  - me-south-1
  - cn-north-1
  - cn-northwest-1
  s3_bucket: ''
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    KubeSphereConsolePassword: override
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  qingcloud-kubesphere-defaults:
    parameters:
      Alerting: 'false'
      AvailabilityZones: $[taskcat_genaz_3]
      Devops: 'false'
      KeyPairName: override
      KubeSphereLicenseKey: OVERRIDE
      Logging: 'false'
      NodeInstanceType: t3.xlarge
      Notification: 'false'
      Openpitrix: 'false'
      QSS3BucketRegion: $[taskcat_current_region]
      Servicemesh: 'false'
      Events: 'false'
      Auditing: 'false'
      MetricsServer: 'true'
      Networkpolicy: 'false'
    regions:
    - us-east-1
    - ca-central-1
    s3_bucket: ''
    template: templates/kubesphere-master.template.yaml
  qingcloud-kubesphere-china-nw:
    parameters:
      Alerting: 'false'
      AvailabilityZones: $[taskcat_genaz_3]
      Devops: 'false'
      KeyPairName: override
      KubeSphereLicenseKey: OVERRIDE
      Logging: 'false'
      NodeInstanceType: t3.xlarge
      Notification: 'false'
      Openpitrix: 'false'
      Servicemesh: 'false'
      Events: 'false'
      Auditing: 'false'
      MetricsServer: 'true'
      Networkpolicy: 'false'
    regions:
    - cn-northwest-1
    s3_bucket: ''
    template: templates/kubesphere-master.template.yaml
  qingcloud-kubesphere-2az:
    parameters:
      Alerting: 'false'
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      Devops: 'false'
      KeyPairName: override
      KubeSphereLicenseKey: OVERRIDE
      Logging: 'false'
      NodeInstanceType: t3.xlarge
      Notification: 'false'
      Openpitrix: 'false'
      Servicemesh: 'false'
      Events: 'false'
      Auditing: 'false'
      MetricsServer: 'true'
      Networkpolicy: 'false'
    regions:
    - cn-north-1
    - sa-east-1
    s3_bucket: ''
    template: templates/kubesphere-master.template.yaml
