
[.text-center]
[discrete]
== AWS Cloud 上的{partner-product-name}
:doctitle: {partner-product-name} on the AWS Cloud
:!toc:
[.text-left]
include::../{includedir}/introduction.adoc[]

== 概述
include::../{includedir}/overview.adoc[]


== AWS 上的{partner-product-name}
ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/product_description.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/product_description.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

== 费用
include::../{includedir}/cost.adoc[]

ifndef::disable_licenses[]
== 软件许可证
ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/licenses.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/licenses.adoc[]
ifndef::production_build[]
|===
endif::production_build[]
endif::disable_licenses[]

== 架构
ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/architecture.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/architecture.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

== 规划部署

include::../{includedir}/planning_deployment.adoc[]

== 部署步骤
include::../{includedir}/deployment_steps.adoc[]

// == Parameters
// include::../{generateddir}/parameters/index.adoc[]

// additional_info.adoc contains 3 sections: Best Practice, Security & Other information

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/additional_info.adoc`**_
++++
<div class="preview_mode">
++++
endif::production_build[]
include::../{specificdir}/additional_info.adoc[]



ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/faq_troubleshooting.adoc`**_
++++
<div class="preview_mode">
++++
endif::production_build[]
include::../{specificdir}/faq_troubleshooting.adoc[]
ifndef::production_build[]
++++
</div>
++++
endif::production_build[]

ifdef::parameters_as_appendix[]
== Parameter reference

NOTE: Unless you are customizing the Quick Start templates for your own deployment projects, we recommend that you keep the default settings for the parameters labeled `Quick Start S3 bucket name`, `Quick Start S3 bucket
Region`, and `Quick Start S3 key prefix`. Changing these parameter settings automatically updates code references to point to a new Quick Start location. For more information, see the https://aws-quickstart.github.io/option1.html[AWS Quick Start Contributor’s Guide^].

include::../{generateddir}/parameters/index.adoc[]
endif::parameters_as_appendix[]

== 发送反馈

若要提出反馈、提交功能建议或上报问题，请使用此快速入门 https://github.com/aws-quickstart/{quickstart-project-name}[GitHub 仓库^]的 *Issues* 部分。若要提交代码，请参见 https://aws-quickstart.github.io/[Quick Start Contributor’s Guide^]。

== 快速入门参考部署

请参见 https://aws.amazon.com/cn/quickstart/architecture/qingcloud-kubesphere/[AWS 快速入门首页]。


== GitHub 仓库

访问我们的 https://github.com/aws-quickstart/{quickstart-project-name}[GitHub 仓库^] 以下载此快速入门的模板和脚本，发表评论，并和他人分享您的自定义配置。

'''
include::../{includedir}/disclaimer.adoc[]
