// Add any tips or answers to anticipated questions. This could include the following troubleshooting information. If you don’t have any other Q&A to add, change “FAQ” to “Troubleshooting.”

== FAQ

*问：启动此快速入门时提示 `CREATE_FAILED` 错误。*

答：如果 AWS CloudFormation 创建堆栈失败，建议您将 *失败时回滚*设置为 *已禁用*并重启该模板。（此设置在 AWS CloudFormation 控制台 *选项*页面的 *高级*部分下。）设置后，该堆栈的状态会保留，实例会持续运行以便您解决问题。（对于 Windows 系统, 请查看 `%ProgramFiles%\Amazon\EC2ConfigService` 和 `C:\cfn\log` 中的日志文件。）
// If you’re deploying on Linux instances, provide the location for log files on Linux, or omit this sentence.

WARNING: 当您将 *失败时回滚*设置为 *已禁用*时，该堆栈仍然会在 AWS 上持续计费。请确保您在解决问题后删除该堆栈。有关更多信息，请参见 https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/troubleshooting.html[AWS CloudFormation 疑难解答^]。

*问：部署 AWS CloudFormation 模板时提示大小限制错误。*

答：建议您通过此指南中的链接或另一个 S3 存储桶去启动快速入门模板。如果您从本地副本部署模板，或从 S3 存储桶以外的地方部署模板，则可能会发生模板大小限制问题。有关更多信息，请参见 https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS CloudFormation 配额^]。

*问：如何修改语言？*

答：从控制台右上角的下拉菜单中选择 *个人设置*以切换语言。KubeSphere 控制台支持英文、西班牙文、简体中文和繁体中文。