// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For more information, see link:#_planning_the_deployment[Planning the deployment], earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.


=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[Deployment options], earlier in this guide.

[cols=2*]
|===
^|https://fwd.aws/vW77e[Deploy {partner-product-short-name} into a new VPC on AWS^]
^|https://fwd.aws/NxKAW[View template^]

^|https://fwd.aws/XJaW5[Deploy {partner-product-short-name} into an existing VPC on AWS^]
^|https://fwd.aws/X4KMN[View template^]

^|https://fwd.aws/eYPQm[Deploy {partner-product-short-name} into a new VPC on AWS into CN-North-1 Region^]
^|https://aws-quickstart-cn-north-1.s3.cn-north-1.amazonaws.com.cn/quickstart-qingcloud-kubesphere/templates/kubesphere-entrypoint-new-vpc.template.yaml[View template^]

^|https://fwd.aws/Ep9b4[Deploy {partner-product-short-name} into a existing VPC on AWS into CN-Northwest-1 Region^]
^|https://aws-quickstart-cn-northwest-1.s3.cn-northwest-1.amazonaws.com.cn/quickstart-qingcloud-kubesphere/templates/kubesphere-entrypoint-new-vpc.template.yaml[View template^]
|===

WARNING: If you deploy {partner-product-short-name} into an existing VPC, ensure that your VPC has three private subnets in different Availability Zones for the workload instances and that the subnets aren’t shared. This Quick Start doesn’t support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. To allow the instances to download packages and software without exposing them to the internet, the subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables. +
 +
Also, ensure that the domain name in the DHCP options is configured, as explained in the http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP options sets^]. When you launch the Quick Start, provide your VPC settings.

Each deployment takes about {deployment_time} to complete.

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-short-name} is built. The template launches in the {default_deployment_region} Region by default.

NOTE: This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[Amazon Elastic File System endpoints and quotas^].

[start=3]
. On the *Create stack* page, keep the default setting for the template, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.

//In the following tables, parameters are listed by category and described separately for the two deployment options:

//* Parameters for deploying {partner-product-short-name} into a new VPC
//* Parameters for deploying {partner-product-short-name} into an existing VPC



